PROJECT_NAME: slide-adaptor
NAMESPACE: slide-adaptor
IMAGE: getslideapp/slide-adaptor
CELERY_ID: slide-adaptor-local
VIRTUAL_HOST: slide-adaptor.getslideapp.com
VENV_PYTHON: /Users/tejogol/miniconda2/envs/django-starter/bin/python
ENV_FILE: .local.env
POSTGRES_1_PORT_5432_TCP_PORT: 5432
